# Generated by Django 4.0.1 on 2022-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegAndAuth', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Mess',
        ),
        migrations.AlterField(
            model_name='message',
            name='EncryptMessage',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='UserId',
            field=models.IntegerField(max_length=250, null=True),
        ),
    ]
